version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: restaurant_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  nestjs-app:
    build: .
    container_name: nestjs_app_container
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: restaurant_db
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: ['npm', 'run', 'start']

volumes:
  mysql_data:
