version: '3.8'

services:
  mysql_container:
    image: mysql:8.4
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: restaurant_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    networks:
      - mynetwork

  nestjs_app_container:
    build: .
    container_name: nestjs_app_container
    restart: always
    depends_on:
      - mysql_container
    env_file:
      - .env
    environment:
      DB_HOST: mysql_container
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: restaurant_db
    ports:
      - '3000:3000'
    networks:
      - mynetwork
    command: npm run start:dev

networks:
  mynetwork:
